/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.giusistemasalud;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import vistas.CentroSalud;
import vistas.CitasAnteriores;
import vistas.Enfermeros;
import vistas.Medicos;
import vistas.NotaClinica;
import vistas.Pacientes;
import vistas.princi;

/**
 *
 * @author diego
 */
public class Dashborad extends javax.swing.JFrame {

    /**
     * Creates new form Dashborad
     */
    public Dashborad() {
        initComponents();
        InitStyles();
        inicio();
    }
    
    private void InitStyles(){
        pestaña.putClientProperty("FlatLaf.style", "font: 28 $light.font");
        pestaña.setForeground(Color.white);
        appNombre.putClientProperty("FlatLaf.style", "font: 14 $light.font");
        appNombre.setForeground(Color.white);
        
    }
    
    private void inicio(){
        princi init1 = new princi();
        //Medicos init1 = new Medicos();
        ShowPanel(init1);
       
        
    }
    
    
    
    private  void ShowPanel(JPanel p){
         p.setSize(750,430);
         p.setLocation(0, 0);
        
       content.removeAll();
       content.add(p,BorderLayout.CENTER);
       content.revalidate();
       content.repaint();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        appNombre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BotonInicio = new javax.swing.JButton();
        BotonCentroSalud = new javax.swing.JButton();
        BotonMedicos = new javax.swing.JButton();
        BotonEnfermeros = new javax.swing.JButton();
        BotonNotaClinica = new javax.swing.JButton();
        BotonPaciente = new javax.swing.JButton();
        BotonCitasAnteriores = new javax.swing.JButton();
        Barra = new javax.swing.JPanel();
        pestaña = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1002, 708));
        setMinimumSize(new java.awt.Dimension(1002, 708));
        setPreferredSize(new java.awt.Dimension(1002, 708));
        setResizable(false);

        background.setMaximumSize(new java.awt.Dimension(1050, 660));
        background.setMinimumSize(new java.awt.Dimension(1050, 660));
        background.setPreferredSize(new java.awt.Dimension(1050, 660));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(13, 71, 161));

        appNombre.setBackground(new java.awt.Color(13, 71, 161));
        appNombre.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        appNombre.setForeground(new java.awt.Color(255, 255, 255));
        appNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appNombre.setText("App Gestion Sanitaria ");

        BotonInicio.setBackground(new java.awt.Color(13, 71, 140));
        BotonInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonInicio.setForeground(new java.awt.Color(255, 255, 255));
        BotonInicio.setText("Inicio");
        BotonInicio.setBorder(null);
        BotonInicio.setBorderPainted(false);
        BotonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });

        BotonCentroSalud.setBackground(new java.awt.Color(13, 71, 170));
        BotonCentroSalud.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonCentroSalud.setForeground(new java.awt.Color(255, 255, 255));
        BotonCentroSalud.setText("Centros de Salud");
        BotonCentroSalud.setBorder(null);
        BotonCentroSalud.setBorderPainted(false);
        BotonCentroSalud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCentroSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCentroSaludActionPerformed(evt);
            }
        });

        BotonMedicos.setBackground(new java.awt.Color(13, 71, 156));
        BotonMedicos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonMedicos.setForeground(new java.awt.Color(255, 255, 255));
        BotonMedicos.setText("Medicos");
        BotonMedicos.setBorder(null);
        BotonMedicos.setBorderPainted(false);
        BotonMedicos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMedicosActionPerformed(evt);
            }
        });

        BotonEnfermeros.setBackground(new java.awt.Color(13, 71, 166));
        BotonEnfermeros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonEnfermeros.setForeground(new java.awt.Color(255, 255, 255));
        BotonEnfermeros.setText("Enfermeros");
        BotonEnfermeros.setBorder(null);
        BotonEnfermeros.setBorderPainted(false);
        BotonEnfermeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEnfermeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnfermerosActionPerformed(evt);
            }
        });

        BotonNotaClinica.setBackground(new java.awt.Color(13, 71, 180));
        BotonNotaClinica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonNotaClinica.setForeground(new java.awt.Color(255, 255, 255));
        BotonNotaClinica.setText("Nota Clinica");
        BotonNotaClinica.setBorder(null);
        BotonNotaClinica.setBorderPainted(false);
        BotonNotaClinica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonNotaClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNotaClinicaActionPerformed(evt);
            }
        });

        BotonPaciente.setBackground(new java.awt.Color(13, 71, 174));
        BotonPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonPaciente.setForeground(new java.awt.Color(255, 255, 255));
        BotonPaciente.setText("Pacientes");
        BotonPaciente.setBorder(null);
        BotonPaciente.setBorderPainted(false);
        BotonPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPacienteActionPerformed(evt);
            }
        });

        BotonCitasAnteriores.setBackground(new java.awt.Color(13, 71, 180));
        BotonCitasAnteriores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonCitasAnteriores.setForeground(new java.awt.Color(255, 255, 255));
        BotonCitasAnteriores.setText("Citas Anteriores");
        BotonCitasAnteriores.setBorder(null);
        BotonCitasAnteriores.setBorderPainted(false);
        BotonCitasAnteriores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCitasAnteriores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCitasAnterioresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(BotonCentroSalud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonMedicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonEnfermeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonNotaClinica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonCitasAnteriores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(appNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(BotonMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonEnfermeros, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonCentroSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(BotonPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(BotonCitasAnteriores, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonNotaClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 250, 650));

        Barra.setBackground(new java.awt.Color(25, 118, 210));

        pestaña.setBackground(new java.awt.Color(25, 118, 210));
        pestaña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pestaña.setForeground(new java.awt.Color(255, 255, 255));
        pestaña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pestaña.setText("Inicio");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(BarraLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(pestaña, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(pestaña)
                .addGap(26, 26, 26)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        background.add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 150, 740, 520));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        titulo1.setBackground(new java.awt.Color(25, 118, 210));
        titulo1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("Datos del Sistema Sanitario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 740, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCitasAnterioresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCitasAnterioresActionPerformed
        pestaña.setText("Citas Anteriores");
        ShowPanel(new CitasAnteriores());
    }//GEN-LAST:event_BotonCitasAnterioresActionPerformed

    private void BotonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPacienteActionPerformed
        pestaña.setText("Pacientes");
        ShowPanel(new Pacientes());
    }//GEN-LAST:event_BotonPacienteActionPerformed

    private void BotonNotaClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNotaClinicaActionPerformed
        pestaña.setText("Notas Clinicas");
        ShowPanel(new NotaClinica());
    }//GEN-LAST:event_BotonNotaClinicaActionPerformed

    private void BotonEnfermerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnfermerosActionPerformed
        pestaña.setText("Enfermeros");
        ShowPanel(new Enfermeros());
    }//GEN-LAST:event_BotonEnfermerosActionPerformed

    private void BotonMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMedicosActionPerformed
        //Medicos init1 = new Medicos();
        pestaña.setText("Medicos");
        ShowPanel(new Medicos());
    }//GEN-LAST:event_BotonMedicosActionPerformed

    private void BotonCentroSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCentroSaludActionPerformed
        pestaña.setText("Centros de Salud");
        ShowPanel(new CentroSalud());
    }//GEN-LAST:event_BotonCentroSaludActionPerformed

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        pestaña.setText("Inicio");
        ShowPanel(new princi());
    }//GEN-LAST:event_BotonInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashborad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JButton BotonCentroSalud;
    private javax.swing.JButton BotonCitasAnteriores;
    private javax.swing.JButton BotonEnfermeros;
    private javax.swing.JButton BotonInicio;
    private javax.swing.JButton BotonMedicos;
    private javax.swing.JButton BotonNotaClinica;
    private javax.swing.JButton BotonPaciente;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel appNombre;
    private javax.swing.JPanel background;
    private static javax.swing.JPanel content;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pestaña;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
 

}
