/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import com.mycompany.giusistemasalud.CentroSaludImpl;
import java.awt.Color;

/**
 *
 * @author diego
 */
public class CentroSalud extends javax.swing.JPanel {

    /**
     * Creates new form CentroSalud
     */
    public CentroSalud() {
        initComponents();
        InitStyles();
    }
    
        private void InitStyles(){
        EtiquetaComunidad.putClientProperty("FlatLaf.style", "font: 14 $light.font");
        EtiquetaComunidad.setForeground(Color.BLACK);
        EtiquetaEspecialidad.putClientProperty("FlatLaf.style", "font: 14 $light.font");
        EtiquetaEspecialidad.setForeground(Color.BLACK);
        //textoPanel.putClientProperty("FlatLaf.style", "font: 16 $light.font");
        //textoPanel.setForeground(Color.BLACK);
        textoArea.putClientProperty("FlatLaf.style", "font: 16 $light.font");
        textoArea.setForeground(Color.BLACK);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jScrollPaneComunidades = new javax.swing.JScrollPane();
        ListaComunidades = new javax.swing.JList<>();
        EtiquetaEspecialidad = new javax.swing.JLabel();
        jScrollPaneEspecialidad = new javax.swing.JScrollPane();
        ListaEspecialidades = new javax.swing.JList<>();
        BotonBuscar = new javax.swing.JButton();
        textoPanel = new javax.swing.JScrollPane();
        textoArea = new javax.swing.JTextArea();
        EtiquetaComunidad = new javax.swing.JLabel();

        ListaComunidades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pais Vasco", "Navarra", "Aragon", "Islas Baleares", "Islas Canarias", "Andalucia", "Cataluña", "Galicia", "Comunidad Valenciana", "Castilla y Leon", "Cantabria", "Murcia", "Extremadura", "Asturias", "La Rioja", "Castilla-La Mancha" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneComunidades.setViewportView(ListaComunidades);

        EtiquetaEspecialidad.setText("Centros de Salud por Especialidad");

        ListaEspecialidades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Alergología e inmunología clínica", "Anestesiología y reanimación", "Angiología y cirugía vascular", "Cardiología", "Cirugía cardiovascular", "Cirugía general y del aparato digestivo", "Cirugía maxilofacial", "Cirugía ortopédica y traumatología", "Cirugía pediátrica", "Cirugía plástica, estética y reparadora", "Cirugía torácica", "Dermatología médico-quirúrgica y venereología", "Endocrinología y nutrición", "Farmacología clínica", "Gastroenterología", "Genética clínica", "Geriatría", "Ginecología y obstetricia", "Hematología y hemoterapia", "Infectología", "Inmunología", "Medicina de la educación física y del deporte", "Medicina del trabajo", "Medicina deportiva", "Medicina familiar y comunitaria", "Medicina intensiva", "Medicina interna", "Medicina legal y forense", "Medicina nuclear", "Medicina preventiva y salud pública", "Medicina del sueño", "Nefrología", "Neumología", "Neurocirugía", "Neurofisiología clínica", "Neurología", "Obstetricia y ginecología", "Oftalmología", "Oncología médica", "Oncología radioterápica", "Otorrinolaringología", "Microbiología y parasitología", "Radiodiagnóstico", "Radiofísica hospitalaria", "Rehabilitación", "Reumatología", "Salud mental", "Toxicología", "Urología", "Pediatría", "Psiquiatría", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneEspecialidad.setViewportView(ListaEspecialidades);

        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        textoArea.setColumns(20);
        textoArea.setRows(5);
        textoPanel.setViewportView(textoArea);

        EtiquetaComunidad.setText("Centros de Salud por Comunidad");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoPanel)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneComunidades, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EtiquetaComunidad))
                        .addGap(52, 52, 52)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(EtiquetaEspecialidad)
                                .addGap(104, 104, 104)
                                .addComponent(BotonBuscar)))
                        .addGap(0, 190, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EtiquetaComunidad)
                        .addComponent(EtiquetaEspecialidad))
                    .addComponent(BotonBuscar))
                .addGap(15, 15, 15)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneComunidades, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(textoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        
        if(ListaComunidades.getSelectedValue() != null){
            String res = "";
            CentroSaludImpl prob = new CentroSaludImpl();
            res = prob.buscarCentroSaludPorComunidades(ListaComunidades.getSelectedValue());
            textoArea.setText(res);
            ListaComunidades.setSelectedValue(null, true);
            textoArea.setCaretPosition(0);
        }
        
        if(ListaEspecialidades.getSelectedValue() != null){
            String res = "";
            CentroSaludImpl prob = new CentroSaludImpl(); 
            res = prob.buscarCentroSaludPorEspecialidad(ListaEspecialidades.getSelectedValue());
            textoArea.setText(res);
            ListaEspecialidades.setSelectedValue(null, true);
            textoArea.setCaretPosition(0); 
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JLabel EtiquetaComunidad;
    private javax.swing.JLabel EtiquetaEspecialidad;
    private javax.swing.JList<String> ListaComunidades;
    private javax.swing.JList<String> ListaEspecialidades;
    private javax.swing.JPanel bg;
    private javax.swing.JScrollPane jScrollPaneComunidades;
    private javax.swing.JScrollPane jScrollPaneEspecialidad;
    private javax.swing.JTextArea textoArea;
    private javax.swing.JScrollPane textoPanel;
    // End of variables declaration//GEN-END:variables
}
