/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import com.mycompany.giusistemasalud.EnfermerosImpl;
import java.awt.Color;

/**
 *
 * @author diego
 */
public class Enfermeros extends javax.swing.JPanel {

    /**
     * Creates new form Enfermeros
     */
    public Enfermeros() {
        initComponents();
        InitStyles();
    }
    
           private void InitStyles(){
        EtiquetaBuscaEnfermero.putClientProperty("FlatLaf.style", "font: 14 $light.font");
        EtiquetaBuscaEnfermero.setForeground(Color.BLACK);
        EtiBuscarPorEspecialidad.putClientProperty("FlatLaf.style", "font: 14 $light.font");
        EtiBuscarPorEspecialidad.setForeground(Color.BLACK);
        texto.putClientProperty("FlatLaf.style", "font: 16 $light.font");
        texto.setForeground(Color.BLACK);
        TextfieldDNI.putClientProperty("JTextField.placeholderText", "Ingrese DNI");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EtiquetaBuscaEnfermero = new javax.swing.JLabel();
        TextfieldDNI = new javax.swing.JTextField();
        EtiBuscarPorEspecialidad = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaEspecialidades = new javax.swing.JList<>();
        BotonBuscarEnfermero = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();

        EtiquetaBuscaEnfermero.setText("Buscar Enfermero");
        EtiquetaBuscaEnfermero.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        TextfieldDNI.setText("Ingrese DNI");
        TextfieldDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextfieldDNIMouseClicked(evt);
            }
        });
        TextfieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldDNIActionPerformed(evt);
            }
        });

        EtiBuscarPorEspecialidad.setText("Buscar Enfermeros por Especialidad");

        ListaEspecialidades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Alergología e inmunología clínica", "Anestesiología y reanimación", "Angiología y cirugía vascular", "Cardiología", "Cirugía cardiovascular", "Cirugía general y del aparato digestivo", "Cirugía maxilofacial", "Cirugía ortopédica y traumatología", "Cirugía pediátrica", "Cirugía plástica, estética y reparadora", "Cirugía torácica", "Dermatología médico-quirúrgica y venereología", "Endocrinología y nutrición", "Farmacología clínica", "Gastroenterología", "Genética clínica", "Geriatría", "Ginecología y obstetricia", "Hematología y hemoterapia", "Infectología", "Inmunología", "Medicina de la educación física y del deporte", "Medicina del trabajo", "Medicina deportiva", "Medicina familiar y comunitaria", "Medicina intensiva", "Medicina interna", "Medicina legal y forense", "Medicina nuclear", "Medicina preventiva y salud pública", "Medicina del sueño", "Nefrología", "Neumología", "Neurocirugía", "Neurofisiología clínica", "Neurología", "Obstetricia y ginecología", "Oftalmología", "Oncología médica", "Oncología radioterápica", "Otorrinolaringología", "Microbiología y parasitología", "Radiodiagnóstico", "Radiofísica hospitalaria", "Rehabilitación", "Reumatología", "Salud mental", "Toxicología", "Urología", "Pediatría", "Psiquiatría", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListaEspecialidades);

        BotonBuscarEnfermero.setText("Buscar");
        BotonBuscarEnfermero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarEnfermeroActionPerformed(evt);
            }
        });

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane3.setViewportView(texto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EtiquetaBuscaEnfermero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextfieldDNI))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EtiBuscarPorEspecialidad)
                                .addGap(90, 90, 90)
                                .addComponent(BotonBuscarEnfermero))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaBuscaEnfermero)
                    .addComponent(EtiBuscarPorEspecialidad)
                    .addComponent(BotonBuscarEnfermero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextfieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextfieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextfieldDNIActionPerformed

    private void BotonBuscarEnfermeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarEnfermeroActionPerformed
       
        EnfermerosImpl prob = new EnfermerosImpl();
        
        String res;
       

        if(TextfieldDNI.getText().length() == 9){
            //System.out.println(dniTextField.getText().length());
            //System.out.println("Entra en buscar");
            res = prob.buscarEnfermero(TextfieldDNI.getText());
            texto.setText(res);
            texto.setCaretPosition(0);
            TextfieldDNI.setText("");
        }
        else if (ListaEspecialidades.getSelectedValue() != null){
            //System.out.println(ListaEspecialidades.getSelectedValue());
            res = prob.buscarEnfermerosPorEspecialidad(ListaEspecialidades.getSelectedValue());
            System.out.println(res);
            texto.setTabSize(900);
            texto.setText(res);
            texto.setCaretPosition(0);
            
        }

    }//GEN-LAST:event_BotonBuscarEnfermeroActionPerformed

    private void TextfieldDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextfieldDNIMouseClicked
        TextfieldDNI.setText("");
    }//GEN-LAST:event_TextfieldDNIMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarEnfermero;
    private javax.swing.JLabel EtiBuscarPorEspecialidad;
    private javax.swing.JLabel EtiquetaBuscaEnfermero;
    private javax.swing.JList<String> ListaEspecialidades;
    private javax.swing.JTextField TextfieldDNI;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
