/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import com.mycompany.giusistemasalud.MedicosImpl;
import db.DatabaseSistemaSalud;
import interfaces.MedicosInterface;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author diego
 */
public class Medicos extends javax.swing.JPanel {
    

    /**
     * Creates new form Medicos
     */
    public Medicos() {
        initComponents();
        InitStyles();
    }
    
       private void InitStyles(){
        EtiquetaBuscarMedico.putClientProperty("FlatLaf.style", "font: 14 $light.font");
        EtiquetaBuscarMedico.setForeground(Color.BLACK);
        //EtiquetaBuscarMedicoComunidad.putClientProperty("FlatLaf.style", "font: 14 $light.font");
        //EtiquetaBuscarMedicoComunidad.setForeground(Color.BLACK);
        EtiBuscarPorEspecialidad.putClientProperty("FlatLaf.style", "font: 14 $light.font");
        EtiBuscarPorEspecialidad.setForeground(Color.BLACK);
        dniTextField.putClientProperty("JTextField.placeholderText", "Ingrese DNI");
        texto.putClientProperty("FlatLaf.style", "font: 16 $light.font");
        texto.setForeground(Color.BLACK);
        
    } 
     
   
    /*
    private void ShowPanel(JPanel p){
         p.setSize(750,430);
         p.setLocation(0, 0);
        
       content.removeAll();
       content.add(p,BorderLayout.CENTER);
       content.revalidate();
       content.repaint();
    } */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        EtiquetaBuscarMedico = new javax.swing.JLabel();
        BotonBuscarMedico = new javax.swing.JButton();
        EtiBuscarPorEspecialidad = new javax.swing.JLabel();
        dniTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaEspecialidades = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();

        EtiquetaBuscarMedico.setText("Buscar Medico");

        BotonBuscarMedico.setText("Buscar");
        BotonBuscarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarMedicoActionPerformed(evt);
            }
        });

        EtiBuscarPorEspecialidad.setText("Buscar especialidad");

        dniTextField.setText("Ingrese DNI");
        dniTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dniTextFieldMouseClicked(evt);
            }
        });
        dniTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniTextFieldActionPerformed(evt);
            }
        });

        ListaEspecialidades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Alergología e inmunología clínica", "Anestesiología y reanimación", "Angiología y cirugía vascular", "Cardiología", "Cirugía cardiovascular", "Cirugía general y del aparato digestivo", "Cirugía maxilofacial", "Cirugía ortopédica y traumatología", "Cirugía pediátrica", "Cirugía plástica, estética y reparadora", "Cirugía torácica", "Dermatología médico-quirúrgica y venereología", "Endocrinología y nutrición", "Farmacología clínica", "Gastroenterología", "Genética clínica", "Geriatría", "Ginecología y obstetricia", "Hematología y hemoterapia", "Infectología", "Inmunología", "Medicina de la educación física y del deporte", "Medicina del trabajo", "Medicina deportiva", "Medicina familiar y comunitaria", "Medicina intensiva", "Medicina interna", "Medicina legal y forense", "Medicina nuclear", "Medicina preventiva y salud pública", "Medicina del sueño", "Nefrología", "Neumología", "Neurocirugía", "Neurofisiología clínica", "Neurología", "Obstetricia y ginecología", "Oftalmología", "Oncología médica", "Oncología radioterápica", "Otorrinolaringología", "Microbiología y parasitología", "Radiodiagnóstico", "Radiofísica hospitalaria", "Rehabilitación", "Reumatología", "Salud mental", "Toxicología", "Urología", "Pediatría", "Psiquiatría", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListaEspecialidades);

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane3.setViewportView(texto);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EtiquetaBuscarMedico)
                    .addComponent(dniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(EtiBuscarPorEspecialidad)
                        .addGap(176, 176, 176)
                        .addComponent(BotonBuscarMedico)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaBuscarMedico)
                    .addComponent(EtiBuscarPorEspecialidad)
                    .addComponent(BotonBuscarMedico))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dniTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniTextFieldActionPerformed

    private void BotonBuscarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarMedicoActionPerformed
       // db.DatabaseSistemaSalud.queryEnfermedades();
       MedicosImpl prob = new MedicosImpl(); 
       //prob.queryMedicos();
       String res;
      
       if(dniTextField.getText().length() == 9){
           //System.out.println(dniTextField.getText().length());
           res = prob.buscaMedico(dniTextField.getText());
           texto.setText(res);
           dniTextField.setText("");
       }
       else if (ListaEspecialidades.getSelectedValue() != null){
           //System.out.println(ListaEspecialidades.getSelectedValue());
           res = prob.buscarMedicosEspecialidad(ListaEspecialidades.getSelectedValue());
           System.out.println(res);
           texto.setTabSize(900);
           texto.setText(res);
           texto.setCaretPosition(0);
           //dniTextField.putClientProperty("JTextField.placeholderText", "Ingrese el DNI");
       }
           
       
    }//GEN-LAST:event_BotonBuscarMedicoActionPerformed

    private void dniTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dniTextFieldMouseClicked
        dniTextField.setText("");
    }//GEN-LAST:event_dniTextFieldMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarMedico;
    private javax.swing.JLabel EtiBuscarPorEspecialidad;
    private javax.swing.JLabel EtiquetaBuscarMedico;
    private javax.swing.JList<String> ListaEspecialidades;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
